language: java
sudo: required

install: true

script:
  - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar && java -jar BuildTools.jar
  - mvn clean install

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
      addons:
        apt:
          packages:
            - oracle-java9-installer

notifications:
  email: false
